// ANGULAR/landing-page/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  logos_1 = ['assets/icons/icons8-html-5.svg', 'assets/icons/icons8-css3.svg', 'assets/icons/icons8-javascript.svg'];
  logos_2 = ['assets/icons/icons8-bootstrap.svg', 'assets/icons/icons8-react-native.svg', 'assets/icons/icons8-git.svg'];
  social_icons = [
    { name:'assets/icons/icons8-twitter-circled.gif', value_alt:'Twitter',}, 
    { name:'assets/icons/icons8-instagram.gif', value_alt:'Instagram',},
    { name:'assets/icons/icons8-linkedin-circled.gif', value_alt:'Linkedin',},
    { name:'assets/icons/icons8-github.gif', value_alt:'Github',}
  ];
  nav_text = ['Nosotros','Habilidades','Proyectos','Contacto'];
  projects_data = [
    {
      name: 'Adidas Sports',
      value_alt:'adidas-sports',
      path: 'assets/images/adidas.JPG'
    },
    {
      name: 'Nike Experience',
      value_alt:'nike-expeience',
      path: 'assets/images/nike.JPG'
    },
    {
      name: 'Puma Runners',
      value_alt:'puma-runners',
      path: 'assets/images/puma.JPG'
    }
  ];
}

<nav class="navbar is-danger" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <img class="my-img-logo image is-rounded" src="assets/images/pelota_50.png" />
    <h1 class="is-size-2 has-text-weight-bold">RUN APP</h1>
    <button class="navbar-burger is-danger button" aria-label="menu" aria-expanded="false"
      data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </button>
  </div>
  <div class="navbar-menu">
    <div class="navbar-end has-text-centered">
      <a  *ngFor="let item of nav_text" class="navbar-item" href="#">{{item}}</a>
    </div>
  </div>
</nav>
&nbsp;
<section class="hero" id="about">
  <div class="container animate__animated animate__shakeX">
    <div class="columns">
      <div class="column">
        <div class="card">
          <div class="card-image">
            <figure class="image">
              <img src="assets/images/sal.jpg" alt="jane-doe" loading="lazy" class="hero-img" />
            </figure>
          </div>
        </div>
      </div>
      <div class="column is-flex is-align-items-center">
        <div class="card">
          <div class="card-content">
            <p class="title">¡Hay Equipo!</p>
            <div class="content">
              Lorem ipsum leo risus, porta ac consectetur ac, vestibulum at eros. Donec id elit non mi
              porta
              gravida at eget metus. Cum sociis natoque penatibus et magnis dis parturient montes,
              nascetur
              ridiculus mus. Cras mattis consectetur purus sit amet fermentum.
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <div class="box has-text-centered">
          <h1 class="title">Nosotros</h1>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis
            nesciunt excepturi quos obcaecati incidunt voluptatem ipsam sunt ipsum,
            autem deleniti cupiditate molestias quis unde quae totam porro dicta
            iure animi inventore, veniam hic! Omnis nulla, delectus a voluptatibus
          </p>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequuntur
            nostrum dolor minus, libero delectus praesentium perferendis
          </p>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero,
            consequuntur labore? Ea totam voluptas amet!
          </p>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="section has-text-centered">
  <div class="container">
    <h1 class="title">Tecnologías</h1>
    <div class="columns">
      <div *ngFor="let x of logos_1" class="column is-flex is-justify-content-center">
        <div class="card">
          <div class="card-image">
            <figure class="image is-128x128">
              <img src={{x}} alt="" loading="lazy" class="icon icon-card" />
            </figure>
          </div>
        </div>
      </div>
    </div>
    <div class="columns">
      <div *ngFor="let y of logos_2" class="column is-flex is-justify-content-center">
        <div class="card">
          <div class="card-image">
            <figure class="image is-128x128">
              <img src={{y}} alt="" loading="lazy" />
            </figure>
          </div>
        </div>
      </div>    
    </div>
  </div>
</section>


<section class="section has-text-centered">
  <div class="container">
    <h1 class="title">Proyectos Implementados</h1>
    <div class="columns">
      <div *ngFor="let p of projects_data" class="column is-4">
        <div class="card">
          <div class="card-content">
            <p class="has-text-weight-bold"> {{p.name}} </p>
            <div class="content">
              <img src="{{p.path}}" alt="{{p.value_alt}}" loading="lazy" class="project-pic" />
              <p class="project-details">
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas
                ratione vel inventore labore commodi modi quos culpa aut saepe!
                Alias!
              </p>
              <button class="button is-danger is-large is-inverted">¡Click!</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <div class="box">
          <h1 class="title has-text-centered">Contactenos</h1>
          <div class="field">
            <label class="label">Nombre</label>
            <div class="control has-icons-left has-icons-right">
              <input class="input is-danger" type="text" placeholder="Ingrese su Nombre">
              <span class="icon is-small is-left">
                <i class="fas fa-user"></i>
              </span>
              <span class="icon is-small is-right">
                <i class="fas fa-check"></i>
              </span>
            </div>
          </div>

          <div class="field">
            <label class="label">Email</label>
            <div class="control has-icons-left has-icons-right">
              <input class="input is-danger" type="email" placeholder="Ingrese su email">
              <span class="icon is-small is-left">
                <i class="fas fa-envelope"></i>
              </span>
              <span class="icon is-small is-right">
                <i class="fas fa-exclamation-triangle"></i>
              </span>
            </div>
          </div>

          <div class="field">
            <label class="label">Mensaje</label>
            <div class="control">
              <textarea class="textarea is-danger" placeholder="Ingrese su mensaje"></textarea>
            </div>
          </div>

          <div class="field has-text-centered">
            <div class="control">
              <button class="button is-danger is-large is-rounded">Enviar</button>
            </div>

          </div>

        </div>
      </div>
    </div>
  </div>
</section>

<div class="socials">
  <a *ngFor="let i of social_icons" href="#" target="_blank"><img src= {{i.name}} alt={{i.value_alt}} loading="lazy"
      class="image is-32x32" /></a>
</div>


<footer class="footer">
  <div class="content has-text-centered">
    <p class="copy">&copy; Copyright 2021</p>
    <p class="copy">
      Built with &#x2661; by
      <a href="https://algo3.uqbar-project.org/" target="_blank">Algo 3 (Unsam)</a>
    </p>
  </div>
</footer>
<i class="scroll-up is-point is-clickable" id="scroll-up"><img src="assets/icons/icons8-upward-arrow.gif"
    class="image is-32x32" alt="scroll-up" /></i>

// REACT-CHAKRA/src/App.jsx
import React from 'react'
import {
  ChakraProvider,
  Box,
  Text,
  Link,
  VStack,
  Code,
  Grid,
} from '@chakra-ui/react'
import { ColorModeSwitcher } from './ColorModeSwitcher'
import { Logo } from './Logo'
import Navbar from './components/Navbar'
import { extendTheme } from "@chakra-ui/react"

const theme = extendTheme({
  colors: {
    primary: "#f14668",
    white: "#ffffff",
  },
})


function App() {
  return (
    <ChakraProvider theme={theme}>
      <Navbar />
      <section class="hero" id="about">
        <div class="container animate__animated animate__shakeX">
          <div class="columns">
            <div class="column">
              <div class="card">
                <div class="card-image">
                  <figure class="image">
                    <img src="assets/images/sal.jpg" alt="jane-doe" loading="lazy" class="hero-img" />
                  </figure>
                </div>
              </div>
            </div>
            <div class="column is-flex is-align-items-center">
              <div class="card">
                <div class="card-content">
                  <p class="title">¡Hay Equipo!</p>
                  <div class="content">
                    Lorem ipsum leo risus, porta ac consectetur ac, vestibulum at eros. Donec id elit non mi
                    porta
                    gravida at eget metus. Cum sociis natoque penatibus et magnis dis parturient montes,
                    nascetur
                    ridiculus mus. Cras mattis consectetur purus sit amet fermentum.
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section class="section">
        <div class="container">
          <div class="columns">
            <div class="column">
              <div class="box has-text-centered">
                <h1 class="title">Nosotros</h1>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis
                  nesciunt excepturi quos obcaecati incidunt voluptatem ipsam sunt ipsum,
                  autem deleniti cupiditate molestias quis unde quae totam porro dicta
                  iure animi inventore, veniam hic! Omnis nulla, delectus a voluptatibus
                </p>
                <p>
                  Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequuntur
                  nostrum dolor minus, libero delectus praesentium perferendis
                </p>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero,
                  consequuntur labore? Ea totam voluptas amet!
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>


      <section class="section has-text-centered">
        <div class="container">
          <h1 class="title">Tecnologías</h1>
          <div class="columns">
            <div class="column is-flex is-justify-content-center">
              <div class="card">
                <div class="card-image">
                  <figure class="image is-128x128">
                    <img src="assets/icons/icons8-html-5.svg" alt="" loading="lazy"
                      class="icon icon-card" />
                  </figure>
                </div>
              </div>
            </div>
            <div class="column  is-flex is-justify-content-center">
              <div class="card">
                <div class="card-image">
                  <figure class="image is-128x128">
                    <img src="assets/icons/icons8-css3.svg" alt="" loading="lazy" class="icon icon-card" />
                  </figure>
                </div>
              </div>
            </div>
            <div class="column is-flex is-justify-content-center">
              <div class="card">
                <div class="card-image">
                  <figure class="image is-128x128">
                    <img src="assets/icons/icons8-javascript.svg" alt="" loading="lazy"
                      class="icon icon-card" />
                  </figure>
                </div>
              </div>
            </div>
          </div>
          <div class="columns">
            <div class="column is-flex is-justify-content-center">
              <div class="card">
                <div class="card-image">
                  <figure class="image is-128x128">
                    <img src="assets/icons/icons8-bootstrap.svg" alt="" loading="lazy" />
                  </figure>
                </div>
              </div>
            </div>
            <div class="column  is-flex is-justify-content-center">
              <div class="card">
                <div class="card-image">
                  <figure class="image is-128x128">
                    <img src="assets/icons/icons8-react-native.svg" alt="" loading="lazy" />
                  </figure>
                </div>
              </div>
            </div>
            <div class="column is-flex is-justify-content-center">
              <div class="card">
                <div class="card-image">
                  <figure class="image is-128x128">
                    <img src="assets/icons/icons8-git.svg" alt="" loading="lazy" />
                  </figure>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>


      <section class="section has-text-centered">
        <div class="container">
          <h1 class="title">Proyectos Implementados</h1>
          <div class="columns">
            <div class="column is-4">
              <div class="card">
                <div class="card-content">
                  <p class="has-text-weight-bold"> Adidas Sports </p>
                  <div class="content">
                    <img src="assets/images/adidas.JPG" alt="adidas-sports" loading="lazy"
                      class="project-pic" />
                    <p class="project-details">
                      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas
                      ratione vel inventore labore commodi modi quos culpa aut saepe!
                      Alias!
                    </p>
                    <button class="button is-danger is-large is-inverted">¡Click!</button>
                  </div>
                </div>
              </div>
            </div>
            <div class="column is-4">
              <div class="card">
                <div class="card-content">
                  <p class="has-text-weight-bold"> Nike Experience </p>
                  <div class="content">
                    <img src="assets/images/nike.JPG" alt="nike-expeience" loading="lazy"
                      class="project-pic" />
                    <p class="project-details">
                      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas
                      ratione vel inventore labore commodi modi quos culpa aut saepe!
                      Alias!
                    </p>
                    <button class="button is-danger is-large is-inverted">¡Click!</button>
                  </div>
                </div>
              </div>
            </div>
            <div class="column is-4">
              <div class="card">
                <div class="card-content">
                  <p class="has-text-weight-bold"> Puma Runners </p>
                  <div class="content">
                    <img src="assets/images/puma.JPG" alt="puma-runners" loading="lazy"
                      class="project-pic" />
                    <p class="project-details">
                      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas
                      ratione vel inventore labore commodi modi quos culpa aut saepe!
                      Alias!
                    </p>
                    <button class="button is-danger is-large is-inverted">¡Click!</button>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </section>

      <section class="section">
        <div class="container">
          <div class="columns">
            <div class="column">
              <div class="box">
                <h1 class="title has-text-centered">Contactenos</h1>
                <div class="field">
                  <label class="label">Nombre</label>
                  <div class="control has-icons-left has-icons-right">
                    <input class="input is-danger" type="text" placeholder="Ingrese su Nombre" />
                    <span class="icon is-small is-left">
                      <i class="fas fa-user"></i>
                    </span>
                    <span class="icon is-small is-right">
                      <i class="fas fa-check"></i>
                    </span>
                  </div>
                </div>

                <div class="field">
                  <label class="label">Email</label>
                  <div class="control has-icons-left has-icons-right">
                    <input class="input is-danger" type="email" placeholder="Ingrese su email" />
                    <span class="icon is-small is-left">
                      <i class="fas fa-envelope"></i>
                    </span>
                    <span class="icon is-small is-right">
                      <i class="fas fa-exclamation-triangle"></i>
                    </span>
                  </div>
                </div>

                <div class="field">
                  <label class="label">Mensaje</label>
                  <div class="control">
                    <textarea class="textarea is-danger" placeholder="Ingrese su mensaje"></textarea>
                  </div>
                </div>

                <div class="field has-text-centered">
                  <div class="control">
                    <button class="button is-danger is-large is-rounded">Enviar</button>
                  </div>

                </div>

              </div>
            </div>
          </div>
        </div>
      </section>

      <div class="socials">
        <a href="#" target="_blank"><img src="assets/icons/icons8-twitter-circled.gif" alt="Twitter" loading="lazy"
          class="socicon" /></a>
        <a href="#" target="_blank"><img src="assets/icons/icons8-instagram.gif" alt="Instagram" loading="lazy"
          class="socicon" /></a>
        <a href="#" target="_blank"><img src="assets/icons/icons8-linkedin-circled.gif" alt="Linkedin" loading="lazy"
          class="socicon" /></a>
        <a href="#" target="_blank"><img src="assets/icons/icons8-github.gif" alt="Github" class="socicon" /></a>
      </div>


      <footer class="footer">
        <div class="content has-text-centered">
          <p class="copy">&copy; Copyright 2021</p>
          <p class="copy">
            Built with &#x2661; by
            <a href="https://algo3.uqbar-project.org/" target="_blank">Algo 3 (Unsam)</a>
          </p>
        </div>
      </footer>
    </ChakraProvider>
  )
}

export default App
